### ISSUE TITLE
First install

### ISSUE THREAD

**Issue by riso348** [wiktorn/Overpass-API#14]
Hi, please,
i just try to install an image with command in README

```
sudo docker run \
  -e OVERPASS_META=no \
  -e OVERPASS_MODE=clone \
  -e OVERPASS_DIFF_URL=https://planet.openstreetmap.org/replication/minute/ \
  -v /big/docker/overpass_clone_db/:/db \
  -p 8083:80 \
  -i -t \
  --name overpass_world \
  wiktorn/overpass-api
```
but i see only this:

```
2019-05-24 10:55:05,351 CRIT Supervisor running as root (no user in config file)
2019-05-24 10:55:05,355 INFO supervisord started with pid 1
2019-05-24 10:55:06,359 INFO spawned: 'overpass_dispatch' with pid 9
2019-05-24 10:55:06,361 INFO spawned: 'nginx' with pid 10
2019-05-24 10:55:06,364 INFO spawned: 'fcgiwrap' with pid 11
2019-05-24 10:55:06,367 INFO spawned: 'update_overpass' with pid 12
2019-05-24 10:55:06,370 INFO spawned: 'dispatcher_areas' with pid 15
2019-05-24 10:55:06,372 INFO spawned: 'areas_rules' with pid 16
2019-05-24 10:55:06,376 INFO exited: overpass_dispatch (exit status 0; not expected)
2019-05-24 10:55:07,561 INFO spawned: 'overpass_dispatch' with pid 43
2019-05-24 10:55:07,562 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-05-24 10:55:07,562 INFO success: fcgiwrap entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-05-24 10:55:07,562 INFO success: update_overpass entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-05-24 10:55:07,562 INFO success: dispatcher_areas entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-05-24 10:55:07,562 INFO success: areas_rules entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-05-24 10:55:07,574 INFO exited: overpass_dispatch (exit status 0; not expected)
2019-05-24 10:55:10,411 INFO spawned: 'overpass_dispatch' with pid 54
2019-05-24 10:55:10,424 INFO exited: overpass_dispatch (exit status 0; not expected)
2019-05-24 10:55:14,426 INFO spawned: 'overpass_dispatch' with pid 64
2019-05-24 10:55:14,439 INFO exited: overpass_dispatch (exit status 0; not expected)
2019-05-24 10:55:15,431 INFO gave up: overpass_dispatch entered FATAL state, too many start retries too quickly

```
Should i wait or what is wrong? /big/docker/ directory change only changes.log but no data downloaded.

In changes.log i is:
```

Traceback (most recent call last):
  File "/app/venv/bin/pyosmium-get-changes", line 243, in <module>
    exit(main(sys.argv[1:]))
  File "/app/venv/bin/pyosmium-get-changes", line 186, in main
    with open(options.seq_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/db/replicate_id'
/app/bin/update_database --compression-method= --map-compression-method= --flush-size= --db-dir=/db/db
cat: /db/diffs/changes.osm: No such file or directory
For --compression-method, please use "no", "gz", or "lz4" as value.
For --map-compression-method, please use "no", "gz", or "lz4" as value.
Usage: /app/bin/update_database [--db-dir=DIR] [--version=VER] [--meta|--keep-attic] [--flush_size=FLUSH_SIZE] [--compression-method=(no|gz|lz4)] [--map-compression-method=(no|gz|lz4)]

```

**Comment by wiktorn** [comment]
Sorry for this, as clone mode needs to download ~100GB of data I rarely test it. It should be fixed now.
