### ISSUE TITLE
No such file or directory: '/db/replicate_id'

### ISSUE THREAD

**Issue by ArduinoHocam** [wiktorn/Overpass-API#85]
Hi,
I am facing with this error when I passed new URL. It says **No such file or directory: '/db/replicate_id'**
It is working fine with Monaco map, but whenever I pass something different than monaco map, it is failing like this below:
```
alisvndk@alisvndk-G3-3500:~/Desktop$ sudo docker run  -e OVERPASS_META=yes   -e OVERPASS_MODE=init   -e OVERPASS_PLANET_URL=https://transfer.sh/get/5cPvqS/itu_new.osm.bz2   -e OVERPASS_DIFF_URL=http://download.geofabrik.de/europe/turkey-updates/   -e OVERPASS_RULES_LOAD=10   -v /big/docker/overpass_db/:/db   -p 80:80   -i -t wiktorn/overpass-api
Starting supervisord process
2022-01-20 10:24:10,611 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2022-01-20 10:24:10,612 INFO supervisord started with pid 1
2022-01-20 10:24:11,615 INFO spawned: 'overpass_dispatch' with pid 11
2022-01-20 10:24:11,617 INFO spawned: 'nginx' with pid 12
2022-01-20 10:24:11,618 INFO spawned: 'fcgiwrap' with pid 13
2022-01-20 10:24:11,619 INFO spawned: 'update_overpass' with pid 14
2022-01-20 10:24:11,621 INFO spawned: 'dispatcher_areas' with pid 15
2022-01-20 10:24:11,622 INFO spawned: 'areas_rules' with pid 18
/app/bin /
Traceback (most recent call last):
  File "/app/venv/bin/pyosmium-get-changes", line 262, in <module>
    exit(main(sys.argv[1:]))
  File "/app/venv/bin/pyosmium-get-changes", line 200, in main
    with open(options.seq_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/db/replicate_id'
rm: cannot remove '/db/diffs/changes.osc': No such file or directory
<?xml version="1.0" encoding="UTF-8"?>
<osm version="0.6" generator="Overpass API 0.7.57 93a4d346">
<note>The data included in this document is from www.openstreetmap.org. The data is made available under ODbL.</note>

<meta osm_base="2022-01-17T13:54:11Z" areas="2022-01-17T13:54:11Z"/>
```
Do you have any suggestion?
Thanks!

**Comment by ArduinoHocam** [comment]
I've removed /big folder and run the docker run commands with the above parameters again, and it is working fine. Closing the issue but shouldn't the folder be overwritten when I cleaned up docker and run the commands again?
